### ISSUE TITLE
Impossible to use with Firefox

### ISSUE THREAD

**Issue by abonforti** [hassio-addons/addon-ssh#330]
# Problem/Motivation

It's impossible to use the addon from within HA.

## Expected behavior

Addon should work

## Actual behavior

Colored gradients are actually displayed isntead of the characters

## Steps to reproduce

Just launch the webUi

![Screenshot 2021-11-09 at 10 21 07](https://user-images.githubusercontent.com/38355294/140897559-1a699475-9a18-4ed1-af63-1a7d25a1b09c.png)

**Comment by frenck** [comment]
Upstream issue: <https://github.com/tsl0922/ttyd/issues/685>

**Comment by frenck** [comment]
For me, this is fixed by #351

![image](https://user-images.githubusercontent.com/195327/146224904-359ae022-86e3-4d2c-9726-3a9a885f31de.png)

**Comment by SamuelCarson** [comment]
still not working SSH add-on 10.0.0.  How do I get the fix for ttyd #351 installed?

**Comment by frenck** [comment]
That is in 10.0.0, and additionally, see my screenshot above.

The question is, what is different on your setup that causes it...?

**Comment by EpicLPer** [comment]
> still not working SSH add-on 10.0.0. How do I get the fix for ttyd #351 installed?

Try and disable all add-ons you have running and enable them one after another, see if one causes that.  
Also clear your browser cache and maybe delete all Cookies and reauth just in case  
Check the Network tab if something else fails to download, such as the font maybe

**Comment by SamuelCarson** [comment]
Disabled ALL add-ons in Firefox and cleared ALL data (cookies & cache). Deleted SSH add-on in HA and reinstalled 10.0.0. Still does not work. Does work with Edge however this is not an acceptable solution.

**Comment by SamuelCarson** [comment]
what Network tab?

**Comment by SamuelCarson** [comment]
Also updated to Firefox 95.0.1. No change.

**Comment by frenck** [comment]
Sorry to hear that, but I do not have a reproduction senario and am not able to reproduce your problem.

Without such a thing, it will be hard to debug. 🤷‍♂️

**Comment by SamuelCarson** [comment]
What can I do to help?

**Comment by EpicLPer** [comment]
> What can I do to help?

I'd say try another browser first (Edge or Chrome as example) and also try to download a portable version of Firefox and check if it does the same there.  
If it does I'd say it's something with your GPU driver most likely.

You could also go onto one of various WebGL Test websites and see if it does something similar to what you see here.

**Comment by frenck** [comment]
Disable WebGL maybe? Just to see if it resolves it

**Comment by SamuelCarson** [comment]
Updated graphics driver. Verified webgl works with my Firefox by running webgl samples (webglsamples.org). Verified fonts are available by using Microsoft Edge. It still does not work. 
What else can I try?

**Comment by frenck** [comment]
Does it work if you disable webgl?

**Comment by SamuelCarson** [comment]
Disabled webgl in Firefox and verified if is disabled. Still doesn’t work!

**Comment by frenck** [comment]
Sorry to hear that... I really don't know what to do or help you any further.
If there is no indicator on what causes this, doesn't have a reproduction... I won't be able to debug it and/or address it.

**Comment by ComGreed** [comment]
Simply allow canvas usage
![grafik](https://user-images.githubusercontent.com/38788554/148847861-3ce61081-bfe5-4f72-9582-6074994aee2e.png)
