### ISSUE TITLE
Web Terminal suddenly stopped to work

### ISSUE THREAD

**Issue by deviant-studio** [hassio-addons/addon-ssh#39]
Hi guys!
Could anybody help with diagnose of my problem?
It used to work ok, but today i'm not able to connect.
I didn't touch the json config. It looks valid.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 10-hassio: applying... 
[fix-attrs.d] 10-hassio: exited 0.
[fix-attrs.d] 50-ssh: applying... 
[fix-attrs.d] 50-ssh: exited 0.
[fix-attrs.d] 51-sudoers: applying... 
[fix-attrs.d] 51-sudoers: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Hass.io Add-on: SSH & Web Terminal v3.5.0

 SSH & Web Terminal access to your Home Assistant instance

parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 From: 
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured
 By: 
-----------------------------------------------------------
 armhf / Raspbian GNU/Linux 9 (stretch) / HA 0.79.0 / SU 133 / stable
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 02-updates.sh: executing... 

INFO: You are running the latest version of this add-on
[cont-init.d] 02-updates.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
INFO: Password is NOT in the Have I Been Pwned database! Nice!
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 11-disable-notice.sh: executing... 
NOTICE: The SSH daemon has been disabled!
[cont-init.d] 11-disable-notice.sh: exited 0.
[cont-init.d] 20-user.sh: executing... 
[cont-init.d] 20-user.sh: exited 0.
[cont-init.d] 30-link-common-dirs.sh: executing... 
[cont-init.d] 30-link-common-dirs.sh: exited 0.
[cont-init.d] 40-zsh.sh: executing... 
[cont-init.d] 40-zsh.sh: exited 0.
[cont-init.d] 50-ssh-config.sh: executing... 
[cont-init.d] 50-ssh-config.sh: exited 0.
[cont-init.d] 51-host-keys.sh: executing... 
[cont-init.d] 51-host-keys.sh: exited 0.
[cont-init.d] 52-authorized-keys.sh: executing... 
[cont-init.d] 52-authorized-keys.sh: exited 0.
[cont-init.d] 53-user-ssh-folder.sh: executing... 
[cont-init.d] 53-user-ssh-folder.sh: exited 0.
[cont-init.d] 54-share-sessions.sh: executing... 
[cont-init.d] 54-share-sessions.sh: exited 0.
[cont-init.d] 60-docker.sh: executing... 
[cont-init.d] 60-docker.sh: exited 0.
[cont-init.d] 80-user-packages.sh: executing... 
[cont-init.d] 80-user-packages.sh: exited 0.
[cont-init.d] 81-user-scripts.sh: executing... 
[cont-init.d] 81-user-scripts.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting the ttyd daemon
```

the config:
```
{
  "log_level": "info",
  "ssh": {
    "enable": false,
    "port": 22,
    "username": "hassio",
    "password": "***",
    "authorized_keys": [],
    "sftp": false,
    "compatibility_mode": false,
    "allow_agent_forwarding": false,
    "allow_remote_port_forwarding": false,
    "allow_tcp_forwarding": false
  },
  "web": {
    "enable": true,
    "port": 7681,
    "username": "hassio",
    "password": "***",
    "ssl": false,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "share_sessions": true,
  "packages": [],
  "init_commands": []
}
```

**Comment by frenck** [comment]
`INFO: Starting the ttyd daemon`

It starts, but has additional error caused by a new revision of the Hassio Supervisor. 
So it does not look as pretty, but it should work normal.
I'm currently investigating the root cause of this issue and considering possible solutions.

**Comment by sohoclemz** [comment]
Hi,
I have the same issue : 
`Hass.io Add-on: SSH & Web Terminal v3.5.0
 SSH & Web Terminal access to your Home Assistant instance
parse error: Expected string key before ':' at line 1, column 4
ERROR: Unknown HTTP error occured`

**Comment by frenck** [comment]
It is a known issue now @sohoclemz.
It does not stop the add-on from working, it is just annoying.
We are awaiting a release of an updated Hassio Supervisor that fixes this for us.

**Comment by frenck** [comment]
This is fixed in the current master version.

**Comment by HITChris** [comment]
@frenck has the parse error quoted by @sohoclemz been fixed? I still see those warning lines present in other add-ons with 0.84.5 and supervisor 144.

**Comment by HITChris** [comment]
My issue was indeed ResinOS - thanks :)
